### ISSUE TITLE
安卓 11 允许安装未知应用 允许后闪退

### ISSUE THREAD

**Issue by yingzhong27** [yy1300326388/app_installer#5]
这是允许后控制台返回的信息

```
D/CrashReport(11730): >>> com.xx.xxxxxxx.MainActivity onPaused <<<
I/CrashReport-Native(11730): jni_setNativeInfo: key is 14
I/CrashReport-Native(11730): Set native info: isAppForeground(false)
I/GED     (11730): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 29, oppidx_max 29, oppidx_min 0
V/PhoneWindow(11730): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@8827ace, this = DecorView@a4d3def[MainActivity]
Lost connection to device.
```

这是我的环境

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.1165], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web  
[√] Android Studio (version 4.1.0)
[√] Android Studio
[√] Connected device (3 available)

• No issues found!
```
手机为红米 note9  安卓环境为 Android 11

在AndroidManifest.xml中的application标签下 我也添加了应该添加的provider  xml在添加了file_paths文件
```
        <!-- Provider -->
        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
```
请问  如何让安卓11 升级app 如何越过这个权限 或者 允许这个权限而不让程序闪退 
在安卓9上我测试了这个权限 不会造成闪退 唯独安卓11会造成闪退 请问这个咋解决 多谢

**Comment by yy1300326388** [comment]
你的 Apk 路径是在哪里呢？有没有更加详细的崩溃日志呢？

**Comment by yingzhong27** [comment]
@yy1300326388 

> 你的 Apk 路径是在哪里呢？有没有更加详细的崩溃日志呢？

我是用的path_provider插件去获取地址
``` dart 
 // 获取apk存放地址(外部路径)
  Future<String> get _apkLocalPath async {
    final directory = await getExternalStorageDirectory();
    return directory.path;
  }
```

我是这样去获取路径的
实际的地址为 /storage/emulated/0/Android/data/com.ft.anlianghu/files/anlianghu.apk

没有更多的错误报告了

**Comment by yy1300326388** [comment]
你的 @xml/file_paths 文件内容贴一下

**Comment by yy1300326388** [comment]
你可以使用 adb logcat 把崩溃的日志打出来，上面的崩溃是有的，但是你应该在 IDE 中没有显示出来

**Comment by yingzhong27** [comment]
``` xml
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path path="Android/data/com.xxx.xxxxx/" name="files_root" />
    <external-path path="." name="external_storage_root" />
</paths>
```
这是我的 file_path
对了 红米note9 提示过一个异常 说的是 返回为空异常

**Comment by yingzhong27** [comment]
``` xml
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path path="Android/data/com.xxx.xxxxx/" name="files_root" />
    <external-path path="." name="external_storage_root" />
</paths>
```
这是我的 file_path
对了 红米note9 提示过一个异常 说的是 返回为空异常

**Comment by yy1300326388** [comment]
你使用这个 file_path 试试
```
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path path="Android/data/com.xxx.xxx/" name="files_root" />
    <external-path path="." name="external_storage_root" />
    <external-media-path path="." name="external_media_root" />
    <external-path
        name="external-path"
        path="."/>
    <external-cache-path
        name="external-cache-path"
        path="."/>
    <external-files-path
        name="external-files-path"
        path="."/>
    <files-path
        name="files_path"
        path="."/>
    <cache-path
        name="cache-path"
        path="."/>
    <root-path
        name="name"
        path="."/>
</paths>
```

**Comment by yy1300326388** [comment]
你看看是这个https://github.com/yy1300326388/app_installer/issues/2 错误吗？这个在新版本已经解决了，

**Comment by yingzhong27** [comment]
```
08-24 11:32:59.431  1120  1272 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 1000; state: DISABLED
08-24 11:32:59.432  1120  1272 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 1000; state: ENABLED
08-24 11:32:59.460   552   552 D Zygote  : Forked child process 23658
08-24 11:32:59.465  1120  1273 D Boost   : hostingType=service, hostingName={com.android.settings/com.android.settings.dangerousoptions.DangerousOptionsWarningService}, callerPackage=com.android.settings, isSystem=true, isBoostNeeded=false.08-24 11:32:59.465  1120  1273 I ActivityManager: Start proc 23658:com.android.settings:remote/1000 for service {com.android.settings/com.android.settings.dangerousoptions.DangerousOptionsWarningService} caller=com.android.settings
08-24 11:32:59.495 23658 23658 E settings:remot: Not starting debugger since process cannot load the jdwp agent.
08-24 11:32:59.507  1120  2088 V ActivityManager: New death recipient com.android.server.am.ActivityManagerService$AppDeathRecipient@68dcbbf for thread android.os.BinderProxy@32e228c
08-24 11:32:59.528  1120  1404 W SensorService: Dropping 1 cached events (984/984) to save 1/1 new events. 6 events previously dropped
08-24 11:32:59.591 23658 23658 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-24 11:32:59.591 23658 23658 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-24 11:32:59.597 23658 23658 E settings:remot: Invalid ID 0x00000000.
08-24 11:32:59.600 23658 23658 D miuisdk : current sdk level is 24
08-24 11:32:59.600 23658 23658 I miuisdk : initialize without hook
08-24 11:32:59.618 23658 23658 W Linkify.v16: reflect applyLink failed:
08-24 11:32:59.618 23658 23658 W Linkify.v16: miui.reflect.NoSuchMethodException: Couldn't find method android/text/util/Linkify.applyLink(Ljava/lang/String;IILandroid/text/Spannable;)V
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.miui.internal.os.Native.getMethod(Native Method)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at miui.reflect.Method.of(Method.java:35)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.miui.internal.variable.v16.Android_Text_Util_Linkify_class.<clinit>(Android_Text_Util_Linkify_class.java:70)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at java.lang.Class.classForName(Native Method)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at java.lang.Class.forName(Class.java:454)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at java.lang.Class.forName(Class.java:379)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.miui.internal.variable.AbsClassFactory.create(AbsClassFactory.java:24)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.miui.internal.variable.Android_Text_Util_Linkify_class$Factory.<init>(Android_Text_Util_Linkify_class.java:40)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.miui.internal.variable.Android_Text_Util_Linkify_class$Factory.<init>(Android_Text_Util_Linkify_class.java:26)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.miui.internal.variable.Android_Text_Util_Linkify_class$Factory$1.createInstance(Android_Text_Util_Linkify_class.java:32)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.miui.internal.variable.Android_Text_Util_Linkify_class$Factory$1.createInstance(Android_Text_Util_Linkify_class.java:29)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at miui.util.SoftReferenceSingleton.get(SoftReferenceSingleton.java:25)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.miui.internal.variable.Android_Text_Util_Linkify_class$Factory.getInstance(Android_Text_Util_Linkify_class.java:44)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.miui.internal.initialization.OverrideHelper.doInitialize(OverrideHelper.java:37)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at miui.core.SdkManager.initialize(SdkManager.java:99)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at java.lang.reflect.Method.invoke(Native Method)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at miui.external.Application.initializeSdk(Application.java:85)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at miui.external.Application.<init>(Application.java:55)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.android.settings.Application.<init>(Application.java:5)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at java.lang.Class.newInstance(Native Method)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at android.app.Instrumentation.newApplication(Instrumentation.java:1158)08-24 11:32:59.618 23658 23658 W Linkify.v16:   at android.app.LoadedApk.makeApplication(LoadedApk.java:1248)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6826)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at android.app.ActivityThread.access$1500(ActivityThread.java:250)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1989)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at android.os.Handler.dispatchMessage(Handler.java:106)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at android.os.Looper.loop(Looper.java:236)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at android.app.ActivityThread.main(ActivityThread.java:7864)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at java.lang.reflect.Method.invoke(Native Method)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
08-24 11:32:59.618 23658 23658 W Linkify.v16:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
08-24 11:32:59.711 23658 23677 D OneTrackSdk: log on: false, quick upload on: false
08-24 11:32:59.718  1120  2088 D CompatibilityChangeReporter: Compat change id reported: 136274596; UID 1000; state: DISABLED
08-24 11:32:59.718  1120  2088 D CompatibilityChangeReporter: Compat change id reported: 136219221; UID 1000; state: DISABLED
08-24 11:32:59.720 23658 23677 D OneTrackImp: OneTrackImp init : Configuration{appId='31*******74', pluginId='null', channel='xiaomi', international=false, region='null', overrideMiuiRegionSetting=false, mode=APP, GAIDEnable=true, IMSIEnable=true, IMEIEnable=true, ExceptionCatcherEnable=true}
```
感觉不是用一个问题 我也尝试了你发给我的方法 然后去logcat里面去找了这个 但是没怎么看懂 这是个什么异常 不会安卓 = =
我引入你插件时 用的是 1.0.0 是最新的tag了呀  你手中是否有安卓11的手机 你可以自己尝试一下 我用安卓11的手机跑过安卓原生的升级安装 也会去请求位置应用安装 但是 app没有闪退 不知道怎么做到的

**Comment by yingzhong27** [comment]
未知应用安装 不是位置

**Comment by yingzhong27** [comment]
其实 我还使用过别的插件 比如openfile 直接打开文件安装  
 _https://github.com/crazecoder/open_file/issues/159_
你可以去看看这个回答 他告诉我说这是安卓11的机制问题无法解决 可我自己跑原生的时候 看到 同样请求了权限
但是flutter 会闪退 安卓不会 我在想是不是要在同意权限后 重新唤起app 然后执行安装 针对安卓11  对于重新唤起app 要怎么做呢

**Comment by yy1300326388** [comment]
晚上回去试试，现在手上没有 Android 11 的机子

**Comment by yy1300326388** [comment]
有新的进展了给你回复

**Comment by yy1300326388** [comment]
我尝试了 Android 11 确实存在这个问题

**Comment by yingzhong27** [comment]
那你有好的处理办法吗？如果有的话，请回复一下，多谢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月24日(星期二) 晚上9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yy1300326388/app_installer] 安卓 11 允许安装未知应用 允许后闪退 (#5)

**Comment by yy1300326388** [comment]
搜索了一圈，没有啥好的办法，这个是自动重启了

**Comment by yy1300326388** [comment]
但是我看广告的安装是直接提示是否允许安装，没有跳到授权这一步，我想是不是有其他方法可以操作，我尝试一下

**Comment by yy1300326388** [comment]
找到一个解决办法，我稍后更新一下
- 如果是 Android 11 则直接调用安装方法，会弹出如下弹窗，可以直接安装
- 如果是其他版本还是继续走现有逻辑 
![image](https://user-images.githubusercontent.com/8764899/130636057-b2eab4bb-daf8-41cc-907f-daa11fa62082.png)

**Comment by yingzhong27** [comment]
感谢更新，明天我去试一下------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月24日(星期二) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yy1300326388/app_installer] 安卓 11 允许安装未知应用 允许后闪退 (#5)

**Comment by yingzhong27** [comment]
没看到你发新的tags，分支里面也没见更新呀 可以更新一下 我试试

**Comment by yy1300326388** [comment]
Android 8,9,10,11,12 都已测试完毕，稍后发布

**Comment by yingzhong27** [comment]
android11 测试 解决问题了 感谢更新

**Comment by yy1300326388** [comment]
客气啦，非常感谢你的耐心等待
- v0.5.0 非空安全版本
- v1.1.0 空安全版本
